// src/app/leaderboard/traderData.js
export const traders = [
  {
    id: 1,
    rank: 1,
    avatar: "/avatars/avatar1.png",
    name: "Aryan Mehta",
    role: "Day Trader",
    category: "Stocks",
    streak: 12,
    alerts: 34,
    trades: 120,
    avgGain: 8.2,
    xScore: 982,
  },
  {
    id: 2,
    rank: 2,
    avatar: "/avatars/avatar2.png",
    name: "Riya Sharma",
    role: "Swing Trader",
    category: "Options",
    streak: 9,
    alerts: 28,
    trades: 110,
    avgGain: 6.7,
    xScore: 951,
  },
  {
    id: 3,
    rank: 3,
    avatar: "/avatars/avatar3.png",
    name: "Kabir Singh",
    role: "Options Trader",
    category: "Crypto",
    streak: 7,
    alerts: 22,
    trades: 98,
    avgGain: 5.1,
    xScore: 930,
  },
  {
    id: 4,
    rank: 4,
    avatar: "/avatars/avatar4.png",
    name: "Neha Patel",
    role: "Day Trader",
    category: "Stocks",
    streak: 5,
    alerts: 18,
    trades: 80,
    avgGain: 3.9,
    xScore: 870,
  },
  {
    id: 5,
    rank: 5,
    avatar: "/avatars/avatar5.png",
    name: "Siddharth Rao",
    role: "Swing Trader",
    category: "Options",
    streak: 4,
    alerts: 15,
    trades: 75,
    avgGain: 2.5,
    xScore: 850,
  },
  {
    id: 6,
    rank: 6,
    avatar: "/avatars/avatar6.png",
    name: "Priya Nair",
    role: "Options Trader",
    category: "Crypto",
    streak: 3,
    alerts: 12,
    trades: 60,
    avgGain: -1.2,
    xScore: 810,
  },
  {
    id: 7,
    rank: 7,
    avatar: "/avatars/avatar7.png",
    name: "Manish Gupta",
    role: "Day Trader",
    category: "Stocks",
    streak: 2,
    alerts: 10,
    trades: 55,
    avgGain: 0.8,
    xScore: 790,
  },
  {
    id: 8,
    rank: 8,
    avatar: "/avatars/avatar8.png",
    name: "Ananya Das",
    role: "Swing Trader",
    category: "Options",
    streak: 1,
    alerts: 8,
    trades: 40,
    avgGain: -2.3,
    xScore: 760,
  },
  {
    id: 9,
    rank: 9,
    avatar: "/avatars/avatar9.png",
    name: "Rahul Jain",
    role: "Options Trader",
    category: "Crypto",
    streak: 1,
    alerts: 6,
    trades: 30,
    avgGain: -3.7,
    xScore: 740,
  },
  {
    id: 10,
    rank: 10,
    avatar: "/avatars/avatar10.png",
    name: "Sneha Kulkarni",
    role: "Day Trader",
    category: "Stocks",
    streak: 0,
    alerts: 4,
    trades: 20,
    avgGain: -5.0,
    xScore: 700,
  },
];

export const statHighlights = [
  {
    icon: "🔥",
    title: "Most Active Trader",
    value: "Aryan Mehta",
    accent: "border-[#2563EB]",
  },
  {
    icon: "🏆",
    title: "Highest Win Rate",
    value: "Riya Sharma",
    accent: "border-[#22C55E]",
  },
  {
    icon: "⏳",
    title: "Longest Streak",
    value: "Kabir Singh",
    accent: "border-[#FFD700]",
  },
  {
    icon: "🚀",
    title: "Biggest Rank Jump",
    value: "Neha Patel",
    accent: "border-[#EF4444]",
  },
];
